# YYHertz Framework Configuration
# 配置文件格式: YAML

# 应用基础配置
app:
  name: "YYHertz"
  version: "1.0.0"
  environment: "development"  # development, testing, production
  debug: true
  port: 8888
  host: "0.0.0.0"
  timezone: "Asia/Shanghai"

# 数据库配置
database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: ""
  database: "yyhertz"
  charset: "utf8mb4"
  max_idle: 10
  max_open: 100
  max_life: 3600  # 秒
  ssl_mode: "disable"

# Redis配置
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle: 2
  dial_timeout: 5  # 秒
  read_timeout: 3  # 秒

# 日志配置
log:
  level: "info"          # debug, info, warn, error, fatal, panic
  format: "json"         # json, text
  enable_console: true
  enable_file: false
  file_path: "./logs/app.log"
  max_size: 100          # MB
  max_age: 7            # 天
  max_backups: 10
  compress: true
  show_caller: true
  show_timestamp: true

# TLS配置
tls:
  enable: false
  cert_file: ""
  key_file: ""
  min_version: "1.2"
  max_version: "1.3"
  auto_reload: false
  reload_interval: 300

# 中间件配置
middleware:
  # CORS跨域配置
  cors:
    enable: true
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["*"]
    expose_headers: []
    allow_credentials: false
    max_age: 3600

  # 限流配置
  rate_limit:
    enable: false
    rate: 100              # 请求/秒
    burst: 200             # 突发容量
    strategy: "token_bucket"  # token_bucket, sliding_window

  # 认证配置
  auth:
    enable: false
    jwt_secret: "your-secret-key-change-me"
    token_ttl: 24          # 小时
    refresh_ttl: 168       # 小时

# 外部服务配置
services:
  # 邮件服务
  email:
    provider: "smtp"       # smtp, sendgrid, ses
    host: "smtp.gmail.com"
    port: 587
    username: ""
    password: ""
    from: "noreply@example.com"

  # 文件存储
  storage:
    provider: "local"      # local, s3, oss
    local_path: "./uploads"
    bucket: ""
    region: ""
    access_key: ""
    secret_key: ""
    cdn_domain: ""

# 监控配置
monitor:
  enable: false
  endpoint: "/metrics"
  interval: 30          # 秒
  timeout: 10           # 秒
